### ISSUE TITLE
relative import is broken in python3.7?

### ISSUE THREAD

**Issue by podhmo** [podhmo/magicalimport#19]
https://github.com/podhmo/swagger-marshmallow-codegen/issues/102#issuecomment-780464569

**Comment by podhmo** [comment]
```
Traceback (most recent call last):
  File "/home/sevni/.pyenv/versions/acapy1/bin/swagger-marshmallow-codegen", line 10, in <module>
    sys.exit(main())
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/swagger_marshmallow_codegen/cmd.py", line 58, in main
    driver = import_symbol(driver_cls, cwd=True)(config)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 142, in import_symbol
    module = import_module(module_path, here=here, sep=sep, _depth=_depth, cwd=cwd)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 130, in import_module
    return import_module_original(module_path)
  File "/home/sevni/.pyenv/versions/3.7.5/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for './mydriver'
```

**Comment by podhmo** [comment]
cannot reproduce it.

```
$ python -V
Python 3.7.8
```

```console
$ python main.py ./hello.py:hello
<function hello at 0x101314b00>
hello
```

main.py

```py
from magicalimport import import_symbol
import sys

path = sys.argv[1]
fn = import_symbol(path, cwd=True)

print(fn)
fn()
```

hello.py

```py
def hello():
    print("hello")
```

**Comment by podhmo** [comment]
error is occurred in https://github.com/python/cpython/blob/37ba7531a59a0a2b240a86f7e2adfb1b1cd8ac0c/Lib/importlib/__init__.py#L109-L127

**Comment by podhmo** [comment]
ok, this is typo. `foo:foo` is incorrect. `foo.py:foo` is correct.
